spring:
  data:
    # redis配置，自行修改
    redis:
      host: redis.nat.k92.top
      port: 6379
      password: Anzu928495870/
      database: 8

khronos:
  morning-start-file-dir: ./pic/morning-start
  morning-end-file-dir: ./pic/morning-end
  afternoon-start-file-dir: ./pic/afternoon-start
  afternoon-end-file-dir: ./pic/afternoon-end
  night-add-file-dir: ./pic/night-add
  location-list:
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北66米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北51米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北61米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北62米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北73米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北81米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北83米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北85米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北87米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北89米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北90米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北92米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北94米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北96米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北100米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北103米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北104米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北108米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北106米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北110米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北113米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北114米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北116米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北118米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北120米
    - 浙江省杭州市萧山区鸿发路若森杭州绿强食品有限公司内,浩宇建材(杭州)运营中心北126米
  # 百度地图api AccessKey，自行申请
  baidu-ak: 6xAw1qbSQ1qrS8jPo7naXJ8RDoHVHI38
  base-url: https://oa.huanweijia.cn/api
  # 将928495870进行base64编码后的结果
  secret: OTI4NDk1ODcw
  scheduled:
    morning-start-cron: "0 15 8 * * ?"
    morning-end-cron: "0 1 12 * * ?"
    afternoon-start-cron: "0 25 13 * * ?"
    afternoon-end-cron: "0 54 17 * * ?"
    night-add-cron: "0 14 19 * * ?"
    # 时间偏移，单位秒，实际打卡时从0 ~ x中生成随机值
    offset: 300
  # 手机号，对应乾图手机号
  phone-number: 18257657990
